name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --name="wdcl2" --onefile --windowed main.py --add-data "oss_helper.py;." --hidden-import=oss2 --hidden-import=PIL._tkinter_finder --hidden-import=PIL.Image --hidden-import=qrcode --hidden-import=reportlab
    
    - name: Create release archive
      run: |
        mkdir release
        copy dist\wdcl2.exe release\
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: release/
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: release/wdcl2.exe
        body: |
          ## 文档处理工具 v${{ github.ref_name }}
          
          ### 下载说明
          - 下载 `wdcl2.exe` 文件
          - 双击运行即可使用
          
          ### 文档链接
          - [README](https://github.com/${{ github.repository }}/blob/main/README.md)
          - [快速开始](https://github.com/${{ github.repository }}/blob/main/快速开始.md)
          - [操作指南](https://github.com/${{ github.repository }}/blob/main/操作指南.md)
          - [OSS配置](https://github.com/${{ github.repository }}/blob/main/OSS配置指南.md)
          
          ### 功能特性
          - ✅ 二维码和PDF生成
          - ✅ 阿里云OSS集成
          - ✅ 支持村/乡目录结构
          - ✅ 批量处理
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
