name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --name="文档处理工具" --onefile --windowed --icon=icon.ico main.py --add-data "oss_helper.py;." --hidden-import=oss2 --hidden-import=PIL._tkinter_finder
    
    - name: Create release archive
      run: |
        mkdir release
        copy dist\文档处理工具.exe release\
        copy README.md release\
        copy 快速开始.md release\
        copy 操作指南.md release\
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: release/
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/文档处理工具.exe
          release/README.md
          release/快速开始.md
          release/操作指南.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
